EMPTY = '---';

DEFAULT_RESOURCE_LABEL = 'resource';

NO_OF_ELEMENTS_TABLE = Meteor.settings.public.no_of_elements_table;

//NO_OF_CHECKS_RETURNED = 6;

DISPLAY_TEXT              = [
  {text:"PEP", value:"PEP"},
  {text:"Watchlist", value:"WATCHLIST"},
  {text:"Special Interest Person", value:"SPECIAL_INTEREST_PERSON"},
  {text:"Special Interest Entity", value:"SPECIAL_INTEREST_ENTITY"},
  {text:"PEP", value:"POLITICALLY_EXPOSED_PERSON"},
  {text:"RCA", value:"RELATIVE_OR_CLOSE_ASSOCIATE"},  
  {text:"Disqualified Entities", value:"DISQUALIFIED_ENTITIES"},
  {text:"Adverse Media", value:"ADVERSE_MEDIA"},
  {text:"Disqualified Entity", value:"BANNED_OR_DISQUALIFIED_ENTITY"},
  {text:"Disqualified Person", value:"BANNED_OR_DISQUALIFIED_PERSON"},
  {text:"Adverse Media Entity", value:"ADVERSE_MEDIA_ENTITY"},
  {text:"Adverse Media Person", value:"ADVERSE_MEDIA_PERSON"},
      
  {text:"also known as", value:"ALSO_KNOWN_AS"},
  {text:"formerly known as", value:"FORMERLY_KNOWN_AS"},
  {text:"maiden name", value:"MAIDEN_NAME"},
  {text:"spelling variation", value:"SPELLING_VARIATION"},
  {text:"expanded language variation", value:"EXPANDED_LANGUAGE_VARIATION"},
  {text:"low quality alias", value:"LOW_QUALITY_AKA"},
  {text:"low quality alias", value:"LOW_QUALITY_ALIAS"},  
  
  {text:"Primary Occupation ", value:"PRIMARY_OCCUPATION"},
  {text:"Previous Occupation", value:"PREVIOUS_ROLE"},
  {text:"Other Role", value:"OTHER_ROLE"},

  {text:"Passport", value:"PASSPORT"},
  {text:"Driving License", value:"DRIVING_LICENSE"},
  {text:"National Insurance Number", value:"NATIONAL_INSURANCE_NUMBER"},
  {text:"National Identity Card", value:"NATIONAL_IDENTITY_CARD"},  
  {text:"Social Security Number", value:"SOCIAL_SECURITY_NUMBER"},
  {text:"Tax ID Number", value:"TAX_ID_NUMBER"},
  {text:"National ID Card", value:"NATIONAL_ID_CARD"},
  {text:"Visa", value:"VISA"},
  {text:"Polling Card", value:"POLLING_CARD"},
  {text:"Residence Permit", value:"RESIDENCE_PERMIT"},
  {text:"Other", value:"OTHER"},
  {text:"Unknown", value:"UNKNOWN"},  

  {text:"Heads & Deputies State/National Government", value:"HEADS_AND_DEPUTIES_STATE_OR_NATIONAL_GOVERNMENT"},
  {text:"National Government Ministers", value:"NATIONAL_GOVERNMENT_MINISTERS"},
  {text:"Members of the National Legislature", value:"MEMBERS_OF_THE_NATIONAL_LEGISLATURE"},
  {text:"Senior Civil Servants-National Government", value:"SENIOR_CIVIL_SERVANTS_NATIONAL_GOVERNMENT"},
  {text:"Senior Civil Servants-Regional Government", value:"SENIOR_CIVIL_SERVANTS_REGIONAL_GOVERNMENT"},
  {text:"Embassy Consular Staff", value:"EMBASSY_AND_CONSULAR_STAFF"},
  {text:"Senior Members of the Armed Forces", value:"SENIOR_MEMBERS_OF_THE_ARMED_FORCES"},
  {text:"Senior Members of the Police Services", value:"SENIOR_MEMBERS_OF_THE_POLICE_SERVICES"},
  {text:"Senior Members of the Secret Services", value:"SENIOR_MEMBERS_OF_THE_SECRET_SERVICES"},
  {text:"Senior Members of the Judiciary", value:"SENIOR_MEMBERS_OF_THE_JUDICIARY"},
  {text:"State Corporation Executives", value:"STATE_CORPORATION_EXECUTIVES"},
  {text:"State Agency Officials", value:"STATE_AGENCY_OFFICIALS"},
  {text:"Heads & Deputy Heads of Regional Government", value:"HEADS_AND_DEPUTY_HEADS_OF_REGIONAL_GOVERNMENT"},
  {text:"Regional Government Ministers", value:"REGIONAL_GOVERNMENT_MINISTERS"},
  {text:"Religious Leaders", value:"RELIGIOUS_LEADERS"},
  {text:"Political Party Officials", value:"POLITICAL_PARTY_OFFICIALS"},
  {text:"International Organisation Officials", value:"INTERNATIONAL_ORGANISATION_OFFICIALS"},  
  {text:"City Mayors", value:"CITY_MAYORS"},
  {text:"Political Pressure and Labour Group Officials", value:"POLITICAL_PRESSURE_AND_LABOUR_GROUP_OFFICIALS"},
  {text:"Other", value:"OTHER"},
  {text:"International NGO Officials", value:"INTERNATIONAL_NGO_OFFICIALS"},
  {text:"Local Public Officials", value:"LOCAL_PUBLIC_OFFICIALS"},
  {text:"International Sporting Organisation Officials", value:"INTERNATIONAL_SPORTING_ORGANISATION_OFFICIALS"},

  {text:"Wife", value:"WIFE"},
  {text:"Husband", value:"HUSBAND"},
  {text:"Brother", value:"BROTHER"},
  {text:"Sister", value:"SISTER"},
  {text:"Son", value:"SON"},
  {text:"Daughter", value:"DAUGHTER"},
  {text:"Mother", value:"MOTHER"},
  {text:"Father", value:"FATHER"},
  {text:"Cousin", value:"COUSIN"},
  {text:"Stepson", value:"STEP_SON"},
  {text:"Stepdaughter", value:"STEP_DAUGHTER"},
  {text:"Brother-in-law", value:"BROTHER_IN_LAW"},
  {text:"Sister-in-law", value:"SISTER_IN_LAW"},
  {text:"Uncle", value:"UNCLE"},
  {text:"Aunt", value:"AUNT"},
  {text:"Mother-in-Law", value:"MOTHER_IN_LAW"},
  {text:"Father-in-Law", value:"FATHER_IN_LAW"},
  {text:"Grandfather", value:"GRANDFATHER"},
  {text:"Grandmother", value:"GRANDMOTHER"},
  {text:"Son-in-law", value:"SON_IN_LAW"},
  {text:"Daughter-in-law", value:"DAUGHTER_IN_LAW"},
  {text:"Niece", value:"NIECE"},
  {text:"Nephew", value:"NEPHEW"},
  {text:"Grandson", value:"GRANDSON"},
  {text:"Granddaughter", value:"GRANDDAUGHTER"},
  {text:"Stepfather", value:"STEPFATHER"},
  {text:"Stepmother", value:"STEPMOTHER"},
  {text:"Business associate", value:"BUSINESS_ASSOCIATE"},
  {text:"Friend", value:"FRIEND"},
  {text:"Financial adviser", value:"FINANCIAL_ADVISER"},
  {text:"Legal adviser", value:"LEGAL_ADVISER"},
  {text:"Colleague", value:"COLLEAGUE"},
  {text:"Agent or representative", value:"AGENT_OR_REPRESENTATIVE"},
  {text:"Employee", value:"EMPLOYEE"},
  {text:"Associate", value:"ASSOCIATE"},
  {text:"Child", value:"CHILD"},
  {text:"Family member", value:"FAMILY_MEMBER"},
  {text:"Political adviser", value:"POLITICAL_ADVISER"},
  {text:"Senior official", value:"SENIOR_OFFICIAL"},
  {text:"Unmarried partner", value:"UNMARRIED_PARTNER"},
  {text:"Same sex spouse", value:"SAME_SEX_SPOUSE"},
  {text:"Employer", value:"EMPLOYER"},
  {text:"Shareholder or owner", value:"SHAREHOLDER_OR_OWNER"},
  {text:"Associated special interest person", value:"ASSOCIATED_SPECIAL_INTEREST_PERSON"},
  {text:"Parent company", value:"PARENT_COMPANY"},
  {text:"Subsidiary", value:"SUBSIDIARY"},
  {text:"Asset", value:"ASSET"},
  
  {text:"MRZ", value:"MRZ"},
  {text:"Image", value:"IMAGE"},
  {text:"Awaiting Validation", value:"AWAITING_VALIDATION"},  
  {text:"Attention", value:"ATTENTION"},
  {text:"Error", value:"ERROR"},  
  {text:"In Progress", value:"IN_PROGRESS"},
  {text:"Confirmed", value:"CONFIRMED"},
  {text:"Clear", value:"DISMISSED"},
  {text:"Clear", value:"CLEAR"},

  {text:"To-do", value:"TO_DO"},
  {text:"In progress", value:"IN_PROGRESS"},
  {text:"Complete", value:"COMPLETE"},

  {text:"Document structure identified", value:"DOCUMENT_RECOGNISED"},
  {text:"Validity of the document outside its issuing country", value:"VALIDITY_OUT_OF_COUNTRY"},
  {text:"Document expiration date identified", value:"DOCUMENT_TYPE_EXPIRATION"},
  {text:"Document issuing country identified", value:"ISSUE_COUNTRY"},
  {text:"Document issuing date identified", value:"ISSUE_DATE"},
  {text:"Document nationality identified", value:"NATIONALITY_MATCH"},

  {text:"Document specimen check", value:"DOCUMENT_SPECIMEN"},
  {text:"Analysis of daylight colours", value:"DAYLIGHT_COLOUR_ANALYSIS"},
  {text:"Analysis of graphical security elements", value:"VISUAL_SECURITY_ELEMENTS"},
  {text:"Analysis of MRZ / document consistency", value:"MRZ_MATCHING_TYPE"},
  {text:"Analysis of MRZ visual format", value:"MRZ_VISUAL_FORMAT"},
  {text:"Analysis of photo location", value:"PHOTO_LOCATION"},

  {text:"Birth date recognised", value:"BIRTH_DATE_RECOGNISED"},
  {text:"Last name recognised", value:"LAST_NAME_RECOGNISED"},
  {text:"Document number recognised", value:"DOC_NUMBER_RECOGNISED"},
  {text:"First name recognised", value:"FIRST_NAME_RECOGNISED"},

  {text:"Consistency of customer's gender", value:"CUSTOMER_GENDER"},
  {text:"Consistency of customer's nationality", value:"CUSTOMER_NATIONALITY"},
  {text:"Consistency of customer's first name", value:"CUSTOMER_FIRST_NAME"},
  {text:"Consistency of customer's birth place", value:"CUSTOMER_BIRTH_PLACE"},
  {text:"Consistency of customer's birth date", value:"CUSTOMER_DOB"},
  {text:"Consistency of customer's last name", value:"CUSTOMER_LAST_NAME"},
  
  {text:"Document expiration check", value:"DOCUMENT_EXPIRATION"},

  {text:"Validity of the MRZ content", value:"MRZ_FIELDS_FORMAT"},
  {text:"MRZ checksum check", value:"MRZ_CHECKSUM"},
  
  {text:"Customer creation", value:"CUSTOMER_CREATED"},
  {text:"Customer screening", value:"CUSTOMER_SCREENING"},    
  {text:"Customer profile change", value:"PERSONAL_DETAILS_UPDATE"},
  {text:"Watchlist screening", value:"WATCHLIST_SCREENING"},  
  {text:"Disqualified entities screening", value:"DISQUALIFIED_ENTITIES_SCREENING"},
  {text:"PEP screening", value:"PEP_SCREENING"},  
  {text:"RCA screening", value:"RCA_SCREENING"},
  {text:"Country risk score change", value:"COUNTRY_SCORE_UPDATE"},
  {text:"Occupation risk score change", value:"OCCUPATION_SCORE_UPDATE"},
]

CUSTOMER_GENDER_OPTIONS   = [
  {text:"-", value:""},
  {text:"Male", value:"MALE"},
  {text:"Female", value:"FEMALE"},
  {text:"Other", value:"OTHER"}]

CUSTOMER_TITLE_OPTIONS    = [
  {text:"-", value:""},
  {text:"Mr", value:"MR"},
  {text:"Mrs", value:"MRS"},
  {text:"Miss", value:"MISS"},
  {text:"Ms", value:"MS"}]

PRIORITY_OPTIONS          = [
  {text:"-", value:""},
  {text:"Low", value:"LOW"},
  {text:"Medium", value:"MEDIUM"},  
  {text:"High", value:"HIGH"}]  

DOCUMENT_TYPE_OPTIONS     = [
  {text:"-", value:""},
  {text:"Passport", value:"PASSPORT"},
  {text:"Driving License", value:"DRIVING_LICENSE"},
  {text:"National Insurance Number", value:"NATIONAL_INSURANCE_NUMBER"},
  {text:"Social Security Number", value:"SOCIAL_SECURITY_NUMBER"},
  {text:"Tax ID Number", value:"TAX_ID_NUMBER"},
  {text:"National ID Card", value:"NATIONAL_ID_CARD"},
  {text:"Visa", value:"VISA"},
  {text:"Polling Card", value:"POLLING_CARD"},
  {text:"Residence Permit", value:"RESIDENCE_PERMIT"},
  {text:"Other", value:"OTHER"}
]

ODD_FREQUENCY_OPTIONS      = [  
  {text:"Daily", value:"DAILY"},
  {text:"Weekly", value:"WEEKLY"},
  {text:"Monthly", value:"MONTHLY"},
]

// _id required for ODD multiselect box
SCREENING_SCOPE_OPTIONS    = [
  {_id:"WATCHLIST", text:"Watchlist", value:"WATCHLIST"},
  {_id:"PEP", text:"PEP", value:"PEP"},
  {_id:"DISQUALIFIED_ENTITIES", text:"Disqualified Entities", value:"DISQUALIFIED_ENTITIES"},
  {_id:"ADVERSE_MEDIA", text:"Adverse Media", value:"ADVERSE_MEDIA"}  
]


ADDRESS_TYPE_OPTIONS      = [
  {text:"-", value:""},
  {text:"Primary", value:"PRIMARY"},
  {text:"Alternative", value:"ALTERNATIVE"},
  {text:"Other", value:"OTHER"}
]

INCORPORATION_TYPE_OPTIONS     = [
  {text:"-", value:""},
  {text:"Sole Trader", value:"SOLE_TRADER"},
  {text:"Private Limited", value:"PRIVATE_LIMITED"},
  {text:"Limited Liability Partnership", value:"LIMITED_LIABILITY_PARTNERSHIP"},
  {text:"Public Limited", value:"PUBLIC_LIMITED"}
]

BUSINESS_PURPOSE_OPTIONS     = [
  {text:"-", value:""},
  {text:"Regulated Entity", value:"REGULATED_ENTITY"},
  {text:"Private Entity", value:"PRIVATE_ENTITY"},
  {text:"Unregulated Fund", value:"UNREGULATED_FUND"},
  {text:"Trust", value:"TRUST"},
  {text:"Foundation", value:"FOUNDATION"},
  {text:"Religious Body", value:"RELIGIOUS_BODY"},
  {text:"Government Entity", value:"GOVERNMENT_ENTITY"},
  {text:"Charity", value:"CHARITY"},
  {text:"Club", value:"CLUB"},
  {text:"Society", value:"SOCIETY"}
]

USER_ROLES = [
  {text:"admin", value:"admin"},  
  {text:"test", value:"test"},
  {text:"live", value:"live"}
]

COUNTRIES = [
  {text:"-", value:""},
  {text:"Afghanistan", value:"AFG", iso2:"AF", flag:"Afghanistan"},
  {text:"Aland Islands", value:"ALA", iso2:"AX", flag:"Aland"},
  {text:"Albania", value:"ALB", iso2:"AL", flag:"Albania"},
  {text:"Algeria", value:"DZA", iso2:"DZ", flag:"Algeria"},
  {text:"American Samoa", value:"ASM", iso2:"AS", flag:"American-Samoa"},
  {text:"Andorra", value:"AND", iso2:"AD", flag:"Andorra"},
  {text:"Angola", value:"AGO", iso2:"AO", flag:"Angola"},
  {text:"Anguilla", value:"AIA", iso2:"AI", flag:"Anguilla"},
  {text:"Antarctica", value:"ATA", iso2:"AQ", flag:"Antarctica"},
  {text:"Antigua and Barbuda", value:"ATG", iso2:"AG", flag:"Antigua-and-Barbuda"},
  {text:"Argentina", value:"ARG", iso2:"AR", flag:"Argentina"},
  {text:"Armenia", value:"ARM", iso2:"AM", flag:"Armenia"},
  {text:"Aruba", value:"ABW", iso2:"AW", flag:"Aruba"},
  {text:"Australia", value:"AUS", iso2:"AU", flag:"Australia"},
  {text:"Austria", value:"AUT", iso2:"AT", flag:"Austria"},
  {text:"Azerbaijan", value:"AZE", iso2:"AZ", flag:"Azerbaijan"},
  {text:"Bahamas", value:"BHS", iso2:"BS", flag:"Bahamas"},
  {text:"Bahrain", value:"BHR", iso2:"BH", flag:"Bahrain"},
  {text:"Bangladesh", value:"BGD", iso2:"BD", flag:"Bangladesh"},
  {text:"Barbados", value:"BRB", iso2:"BB", flag:"Barbados"},
  {text:"Belarus", value:"BLR", iso2:"BY", flag:"Belarus"},
  {text:"Belgium", value:"BEL", iso2:"BE", flag:"Belgium"},
  {text:"Belize", value:"BLZ", iso2:"BZ", flag:"Belize"},
  {text:"Benin", value:"BEN", iso2:"BJ", flag:"Benin"},
  {text:"Bermuda", value:"BMU", iso2:"BM", flag:"Bermuda"},
  {text:"Bhutan", value:"BTN", iso2:"BT", flag:"Bhutan"},
  {text:"Bolivia", value:"BOL", iso2:"BO", flag:"Bolivia"},
  {text:"Bosnia and Herzegovina", value:"BIH", iso2:"BA", flag:"Bosnia-and-Herzegovina"},
  {text:"Botswana", value:"BWA", iso2:"BW", flag:"Botswana"},
  {text:"Bouvet Island", value:"BVT", iso2:"BV", flag:""},
  {text:"Brazil", value:"BRA", iso2:"BR", flag:"Brazil"},
  {text:"British Virgin Islands", value:"VGB", iso2:"VG", flag:"British-Virgin-Islands"},
  {text:"Brunei", value:"BRN", iso2:"BN", flag:"Brunei"},
  {text:"Bulgaria", value:"BGR", iso2:"BG", flag:"Bulgaria"},
  {text:"Burkina Faso", value:"BFA", iso2:"BF", flag:"Burkina-Faso"},
  {text:"Burundi", value:"BDI", iso2:"BI", flag:"Burundi"},
  {text:"Cambodia", value:"KHM", iso2:"KH", flag:"Cambodia"},
  {text:"Cameroon", value:"CMR", iso2:"CM", flag:"Cameroon"},
  {text:"Canada", value:"CAN", iso2:"CA", flag:"Canada"},
  {text:"Cape Verde", value:"CPV", iso2:"CV", flag:"Cape-Verde"},
  {text:"Cayman Islands", value:"CYM", iso2:"KY", flag:"Cayman-Islands"},
  {text:"Central African Republic", value:"CAF", iso2:"CF", flag:"Central-African-Republic"},
  {text:"Chad", value:"TCD", iso2:"TD", flag:"Chad"},
  {text:"Chile", value:"CHL", iso2:"CL", flag:"Chile"},
  {text:"China", value:"CHN", iso2:"CN", flag:"China"},
  {text:"Christmas Island", value:"CXR", iso2:"CX", flag:"Christmas-Island"},
  {text:"Cocos Islands", value:"CCK", iso2:"CC", flag:"Cocos-Keeling-Islands"},
  {text:"Colombia", value:"COL", iso2:"CO", flag:"Colombia"},
  {text:"Comoros", value:"COM", iso2:"KM", flag:"Comoros"},
  {text:"Congo", value:"COD", iso2:"CD", flag:"Democratic-Republic-of-the-Congo"},
  {text:"Cook Islands", value:"COK", iso2:"CK", flag:"Cook-Islands"},
  {text:"Costa Rica", value:"CRI", iso2:"CR", flag:"Costa-Rica"},
  {text:"Croatia", value:"HRV", iso2:"HR", flag:"Croatia"},
  {text:"Cuba", value:"CUB", iso2:"CU", flag:"Cuba"},
  {text:"Cyprus", value:"CYP", iso2:"CY", flag:"Cyprus"},
  {text:"Czech Republic", value:"CZE", iso2:"CZ", flag:"Czech-Republic"},
  {text:"Denmark", value:"DNK", iso2:"DK", flag:"Denmark"},
  {text:"Djibouti", value:"DJI", iso2:"DJ", flag:"Djibouti"},
  {text:"Dominica", value:"DMA", iso2:"DM", flag:"Dominica"},
  {text:"Dominican Republic", value:"DOM", iso2:"DO", flag:"Ecuador"},
  {text:"Ecuador", value:"ECU", iso2:"EC", flag:"Ecuador"},
  {text:"Egypt", value:"EGY", iso2:"EG", flag:"Egypt"},
  {text:"El Salvador", value:"SLV", iso2:"SV", flag:"El-Salvador"},
  {text:"Equatorial Guinea", value:"GNQ", iso2:"GQ", flag:"Equatorial-Guinea"},
  {text:"Eritrea", value:"ERI", iso2:"ER", flag:"Eritrea"},
  {text:"Estonia", value:"EST", iso2:"EE", flag:"Estonia"},
  {text:"Ethiopia", value:"ETH", iso2:"ET", flag:"Ethiopia"},
  {text:"Falkland Islands", value:"FLK", iso2:"FK", flag:"Falkland-Islands"},
  {text:"Faroe Islands", value:"FRO", iso2:"FO", flag:"Faroes"},
  {text:"Fiji", value:"FJI", iso2:"FJ", flag:"Fiji"},
  {text:"Finland", value:"FIN", iso2:"FI", flag:"Finland"},
  {text:"France", value:"FRA", iso2:"FR", flag:"France"},
  {text:"French Guiana", value:"GUF", iso2:"GF", flag:""},
  {text:"French Polynesia", value:"PYF", iso2:"PF", flag:"French-Polynesia"},
  {text:"French Territories", value:"ATF", iso2:"TF", flag:"French-Southern-Territories"},
  {text:"Gabon", value:"GAB", iso2:"GA", flag:"Gabon"},
  {text:"Gambia", value:"GMB", iso2:"GM", flag:"Gambia"},
  {text:"Georgia", value:"GEO", iso2:"GE", flag:"Georgia"},
  {text:"Germany", value:"DEU", iso2:"DE", flag:"Germany"},
  {text:"Ghana", value:"GHA", iso2:"GH", flag:"Ghana"},
  {text:"Gibraltar", value:"GIB", iso2:"GI", flag:"Gibraltar"},
  {text:"Greece", value:"GRC", iso2:"GR", flag:"Greece"},
  {text:"Greenland", value:"GRL", iso2:"GL", flag:"Greenland"},
  {text:"Grenada", value:"GRD", iso2:"GD", flag:"Grenada"},
  {text:"Guadeloupe", value:"GLP", iso2:"GP", flag:""},
  {text:"Guam", value:"GUM", iso2:"GU", flag:"Guam"},
  {text:"Guatemala", value:"GTM", iso2:"GT", flag:"Guatemala"},
  {text:"Guernsey", value:"GGY", iso2:"GG", flag:"Guernsey"},
  {text:"Guinea", value:"GIN", iso2:"GN", flag:"Guinea"},
  {text:"Guinea-Bissau", value:"GNB", iso2:"GW", flag:"Guinea-Bissau"},
  {text:"Guyana", value:"GUY", iso2:"GY", flag:"Guyana"},
  {text:"Haiti", value:"HTI", iso2:"HT", flag:"Haiti"},
  {text:"Heard Island", value:"HMD", iso2:"HM", flag:""},
  {text:"Honduras", value:"HND", iso2:"HN", flag:"Honduras"},
  {text:"Hong Kong", value:"HKG", iso2:"CN", flag:"Hong-Kong"},
  {text:"Hungary", value:"HUN", iso2:"HU", flag:"Hungary"},
  {text:"Iceland", value:"ISL", iso2:"IS", flag:"Iceland"},
  {text:"India", value:"IND", iso2:"IN", flag:"India"},
  {text:"Indonesia", value:"IDN", iso2:"ID", flag:"Indonesia"},
  {text:"Iran", value:"IRN", iso2:"IR", flag:"Iran"},
  {text:"Iraq", value:"IRQ", iso2:"IQ", flag:"Iraq"},
  {text:"Ireland", value:"IRL", iso2:"IE", flag:"Ireland"},
  {text:"Isle of Man", value:"IMN", iso2:"IM", flag:"Isle-of-Man"},
  {text:"Israel", value:"ISR", iso2:"IL", flag:"Israel"},
  {text:"Italy", value:"ITA", iso2:"IT", flag:"Italy"},
  {text:"Ivory Coast", value:"CIV", iso2:"CI", flag:"Cote-dIvoire"},
  {text:"Jamaica", value:"JAM", iso2:"JM", flag:"Jamaica"},
  {text:"Japan", value:"JPN", iso2:"JP", flag:"Japan"},
  {text:"Jersey", value:"JEY", iso2:"JE", flag:"Jersey"},
  {text:"Jordan", value:"JOR", iso2:"JO", flag:"Jordan"},
  {text:"Kazakhstan", value:"KAZ", iso2:"KZ", flag:"Kazakhstan"},
  {text:"Kenya", value:"KEN", iso2:"KE", flag:"Kenya"},
  {text:"Kiribati", value:"KIR", iso2:"KI", flag:"Kiribati"},
  {text:"Kuwait", value:"KWT", iso2:"KW", flag:"Kuwait"},
  {text:"Kyrgyzstan", value:"KGZ", iso2:"KG", flag:"Kyrgyzstan"},
  {text:"Laos", value:"LAO", iso2:"LA", flag:"Laos"},
  {text:"Latvia", value:"LVA", iso2:"LV", flag:"Latvia"},
  {text:"Lebanon", value:"LBN", iso2:"LB", flag:"Lebanon"},
  {text:"Lesotho", value:"LSO", iso2:"LS", flag:"Lesotho"},
  {text:"Liberia", value:"LBR", iso2:"LR", flag:"Liberia"},
  {text:"Libya", value:"LBY", iso2:"LY", flag:"Libya"},
  {text:"Liechtenstein", value:"LIE", iso2:"LI", flag:"Liechtenstein"},
  {text:"Lithuania", value:"LTU", iso2:"LT", flag:"Lithuania"},
  {text:"Luxembourg", value:"LUX", iso2:"LU", flag:"Luxembourg"},
  {text:"Macao", value:"MAC", iso2:"MO", flag:"Macau"},
  {text:"Macedonia", value:"MKD", iso2:"MK", flag:"Macedonia"},
  {text:"Madagascar", value:"MDG", iso2:"MG", flag:"Madagascar"},
  {text:"Malawi", value:"MWI", iso2:"MW", flag:"Malawi"},
  {text:"Malaysia", value:"MYS", iso2:"MY", flag:"Malaysia"},
  {text:"Maldives", value:"MDV", iso2:"MV", flag:"Maldives"},
  {text:"Mali", value:"MLI", iso2:"ML", flag:"Mali"},
  {text:"Malta", value:"MLT", iso2:"MT", flag:"Malta"},
  {text:"Marshall Islands", value:"MHL", iso2:"MH", flag:"Marshall-Islands"},
  {text:"Martinique", value:"MTQ", iso2:"MQ", flag:"Martinique"},
  {text:"Mauritania", value:"MRT", iso2:"MR", flag:"Mauritania"},
  {text:"Mauritius", value:"MUS", iso2:"MU", flag:"Mauritius"},
  {text:"Mayotte", value:"MYT", iso2:"YT", flag:"Mayotte"},
  {text:"Mexico", value:"MEX", iso2:"MX", flag:"Mexico"},
  {text:"Micronesia", value:"FSM", iso2:"FM", flag:"Micronesia"},
  {text:"Moldova", value:"MDA", iso2:"MD", flag:"Moldova"},
  {text:"Monaco", value:"MCO", iso2:"MC", flag:"Monaco"},
  {text:"Mongolia", value:"MNG", iso2:"MN", flag:"Mongolia"},
  {text:"Montenegro", value:"MNE", iso2:"ME", flag:"Montenegro"},
  {text:"Montserrat", value:"MSR", iso2:"MS", flag:"Montserrat"},
  {text:"Morocco", value:"MAR", iso2:"MA", flag:"Morocco"},
  {text:"Mozambique", value:"MOZ", iso2:"MZ", flag:"Mozambique"},
  {text:"Myanmar", value:"MMR", iso2:"MM", flag:"Myanmar"},
  {text:"Namibia", value:"NAM", iso2:"NA", flag:"Namibia"},
  {text:"Nauru", value:"NRU", iso2:"NR", flag:"Nauru"},
  {text:"Nepal", value:"NPL", iso2:"NP", flag:"Nepal"},
  {text:"Netherlands", value:"NLD", iso2:"NL", flag:"Netherlands"},
  {text:"Netherlands Antilles", value:"ANT", iso2:"AN", flag:"Netherlands-Antilles"},
  {text:"New Caledonia", value:"NCL", iso2:"NC", flag:"New-Caledonia"},
  {text:"New Zealand", value:"NZL", iso2:"NZ", flag:"New-Zealand"},
  {text:"Nicaragua", value:"NIC", iso2:"NI", flag:"Nicaragua"},
  {text:"Niger", value:"NER", iso2:"NE", flag:"Niger"},
  {text:"Nigeria", value:"NGA", iso2:"NG", flag:"Nigeria"},
  {text:"Niue", value:"NIU", iso2:"NU", flag:"Niue"},
  {text:"Norfolk Island", value:"NFK", iso2:"NF", flag:"Norfolk-Island"},
  {text:"North Korea", value:"PRK", iso2:"KP", flag:"North-Korea"},
  {text:"Northern Mariana Islands", value:"MNP", iso2:"MP", flag:"Northern-Mariana-Islands"},
  {text:"Norway", value:"NOR", iso2:"NO", flag:"Norway"},
  {text:"Oman", value:"OMN", iso2:"OM", flag:"Oman"},
  {text:"Pakistan", value:"PAK", iso2:"PK", flag:"Pakistan"},
  {text:"Palau", value:"PLW", iso2:"PW", flag:"Palau"},
  {text:"Palestine", value:"PSE", iso2:"PS", flag:"Palestine"},
  {text:"Panama", value:"PAN", iso2:"PA", flag:"Panama"},
  {text:"Papua New Guinea", value:"PNG", iso2:"PG", flag:"Papua-New-Guinea"},
  {text:"Paraguay", value:"PRY", iso2:"PY", flag:"Paraguay"},
  {text:"Peru", value:"PER", iso2:"PE", flag:"Peru"},
  {text:"Philippines", value:"PHL", iso2:"PH", flag:"Philippines"},
  {text:"Pitcairn", value:"PCN", iso2:"PN", flag:"Pitcairn-Islands"},
  {text:"Poland", value:"POL", iso2:"PL", flag:"Poland"},
  {text:"Portugal", value:"PRT", iso2:"PT", flag:"Portugal"},
  {text:"Puerto Rico", value:"PRI", iso2:"PR", flag:"Puerto-Rico"},
  {text:"Qatar", value:"QAT", iso2:"QA", flag:"Qatar"},
  {text:"Reunion", value:"REU", iso2:"RE", flag:""},
  {text:"Romania", value:"ROU", iso2:"RO", flag:"Romania"},
  {text:"Russia", value:"RUS", iso2:"RU", flag:"Russia"},
  {text:"Rwanda", value:"RWA", iso2:"RW", flag:"Rwanda"},
  {text:"Saint Helena", value:"SHN", iso2:"SH", flag:"Saint-Helena"},
  {text:"Saint Kitts and Nevis", value:"KNA", iso2:"KN", flag:"Saint-Kitts-and-Nevis"},
  {text:"Saint Lucia", value:"LCA", iso2:"LC", flag:"Saint-Lucia"},
  {text:"Saint Pierre", value:"SPM", iso2:"PM", flag:""},
  {text:"Saint Vincent", value:"VCT", iso2:"VC", flag:"Saint-Vincent-and-the-Grenadines"},
  {text:"Samoa", value:"WSM", iso2:"WS", flag:"Samoa"},
  {text:"San Marino", value:"SMR", iso2:"SM", flag:"San-Marino"},
  {text:"Sao Tome", value:"STP", iso2:"ST", flag:"Sao-Tome-and-Principe"},
  {text:"Saudi Arabia", value:"SAU", iso2:"SA", flag:"Saudi-Arabia"},
  {text:"Senegal", value:"SEN", iso2:"SN", flag:"Senegal"},
  {text:"Serbia", value:"SRB", iso2:"RS", flag:"Serbia"},
  {text:"Seychelles", value:"SYC", iso2:"SC", flag:"Seychelles"},
  {text:"Sierra Leone", value:"SLE", iso2:"SL", flag:"Sierra-Leone"},
  {text:"Singapore", value:"SGP", iso2:"SG", flag:"Singapore"},
  {text:"Slovakia", value:"SVK", iso2:"SK", flag:"Slovakia"},
  {text:"Slovenia", value:"SVN", iso2:"SI", flag:"Slovenia"},
  {text:"Solomon Islands", value:"SLB", iso2:"SB", flag:"Solomon-Islands"},
  {text:"Somalia", value:"SOM", iso2:"SO", flag:"Somalia"},
  {text:"South Africa", value:"ZAF", iso2:"ZA", flag:"South-Africa"},
  {text:"South Georgia and the South Sandwich Islands", value:"SGS", iso2:"GS", flag:"South-Georgia-and-the-South-Sandwich-Islands"},
  {text:"South Korea", value:"KOR", iso2:"KR", flag:"South-Korea"},
  {text:"South Sudan", value:"SSD", iso2:"SS", flag:"South-Sudan"},
  {text:"Spain", value:"ESP", iso2:"ES", flag:"Spain"},
  {text:"Sri Lanka", value:"LKA", iso2:"LK", flag:"Sri-Lanka"},
  {text:"Sudan", value:"SDN", iso2:"SD", flag:"Sudan"},
  {text:"Suriname", value:"SUR", iso2:"SR", flag:"Suriname"},
  {text:"Swaziland", value:"SWZ", iso2:"SZ", flag:"Swaziland"},
  {text:"Sweden", value:"SWE", iso2:"SE", flag:"Sweden"},
  {text:"Switzerland", value:"CHE", iso2:"CH", flag:"Switzerland"},
  {text:"Syria", value:"SYR", iso2:"SY", flag:"Syria"},
  {text:"Taiwan", value:"TWN", iso2:"TW", flag:"Taiwan"},
  {text:"Tajikistan", value:"TJK", iso2:"TJ", flag:"Tajikistan"},
  {text:"Tanzania", value:"TZA", iso2:"TZ", flag:"Tanzania"},
  {text:"Thailand", value:"THA", iso2:"TH", flag:"Thailand"},
  {text:"Timor-Leste", value:"TLS", iso2:"TL", flag:"timor"},
  {text:"Togo", value:"TGO", iso2:"TG", flag:"Togo"},
  {text:"Tokelau", value:"TKL", iso2:"TK", flag:"Tokelau"},
  {text:"Tonga", value:"TON", iso2:"TO", flag:"Tonga"},
  {text:"Trinidad and Tobago", value:"TTO", iso2:"TT", flag:"Trinidad-and-Tobago"},
  {text:"Tunisia", value:"TUN", iso2:"TN", flag:"Tunisia"},
  {text:"Turkey", value:"TUR", iso2:"TR", flag:"Turkey"},
  {text:"Turkmenistan", value:"TKM", iso2:"TM", flag:"Turkmenistan"},
  {text:"Tuvalu", value:"TUV", iso2:"TV", flag:"Tuvalu"},
  {text:"Uganda", value:"UGA", iso2:"UG", flag:"Uganda"},
  {text:"Ukraine", value:"UKR", iso2:"UA", flag:"Ukraine"},
  {text:"United Arab Emirates", value:"ARE", iso2:"AE", flag:"United-Arab-Emirates"},
  {text:"United Kingdom", value:"GBR", iso2:"GB", flag:"United-Kingdom"},
  {text:"United Kingdom Dependent Territory", value:"GBD", iso2:"GBD", flag:"United-Kingdom"},
  {text:"United Kingdom Overseas National", value:"GBN", iso2:"GBN", flag:"United-Kingdom"},
  {text:"United Kingdom Overseas Citizen", value:"GBO", iso2:"GBO", flag:"United-Kingdom"},
  {text:"United Kingdom Protected Person", value:"GBP", iso2:"GBP", flag:"United-Kingdom"},
  {text:"United Kingdom Subject", value:"GBS", iso2:"GBS", flag:"United-Kingdom"},
  {text:"United States of America", value:"USA", iso2:"US", flag:"United-States"},
  {text:"Uruguay", value:"URY", iso2:"UY", flag:"Uruguay"},
  {text:"US Virgin Islands", value:"VIR", iso2:"VI", flag:"US-Virgin-Islands"},
  {text:"Uzbekistan", value:"UZB", iso2:"UZ", flag:"Uzbekistan"},
  {text:"Vanuatu", value:"VUT", iso2:"VU", flag:"Vanuatu"},
  {text:"Venezuela", value:"VEN", iso2:"VE", flag:"Venezuela"},
  {text:"Vietnam", value:"VNM", iso2:"VN", flag:"Vietnam"},
  {text:"Wallis and Futuna Islands", value:"WLF", iso2:"WF", flag:"Wallis-And-Futuna"},
  {text:"Western Sahara", value:"ESH", iso2:"EH", flag:"Western-Sahara"},
  {text:"Yemen", value:"YEM", iso2:"YE", flag:"Yemen"},
  {text:"Zambia", value:"ZMB", iso2:"ZM", flag:"Zambia"},
  {text:"Zimbabwe", value:"ZWE", iso2:"ZW", flag:"Zimbabwe"},

  {text:"International", value:"111", iso2:"00", flag:"none"},
  {text:"Abkhazia", value:"222", iso2:"00", flag:"none"},
  {text:"Kosovo", value:"333", iso2:"00", flag:"none"},
  {text:"Curaçao", value:"444", iso2:"00", flag:"none"},
  {text:"None", value:"555", iso2:"00",  flag:"none"},
  {text:"St. Maarten", value:"666", iso2:"00", flag:"none"},
  {text:"South Ossetia", value:"777", iso2:"00",  flag:"none"},
  {text:"Turkish Republic of Northern Cyprus", iso2:"00",  value:"888", flag:"none"},
  {text:null, iso2:"00",  value:"COU", flag:"none"},
  {text:null, value:null, iso2:null, flag:"none"},  
];